mysite/map/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'map'

urlpatterns = [
    path('', views.index, name='index_map'),
    path("move", views.move, name='move_map'),
    path("poi", views.poi, name='poi_map'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

from django.conf.urls.static import static
from django.conf import settings

def index(request):
    return render(request,'index.html')

urlpatterns = [
    path('',index,name='root'),
    path("admin/", admin.site.urls),
    path("map/", include("map.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/map/models.py
from django.db import models

# Create your models here.

mysite/map/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

# 인공위성 사진 가져오기
def index(request):
    return render(request, 'map/index.html')

def move(request):
    loc=request.session.get('loc_list',[])
    if request.method=='POST':
        lat = request.POST.get('latitude')
        lon = request.POST.get('longitude')

        loc.append({'lat':lat})
        loc.append({'lon':lon})

    request.session['loc_list'] = loc

    return render(request, 'map/move.html', {'loc_list':loc})

def poi(request):
    return render(request, 'map/poi.html')

mysite/map/templates/map/index.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
  markermap
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'map/style.css' %}">
<div id="mapwrap"> 
    <!-- 지도가 표시될 div -->
    <div id="map" style="width:75%; height:800px;"></div>
    
    <!-- 지도 위에 표시될 마커 카테고리 -->
    <div class="category">
        <ul>
            <li id="portMenu" onclick="changeMarker('port')">
                <span class="ico_comm ico_coffee"></span>
                항포구
            </li>
            <li id="beachMenu" onclick="changeMarker('beach')">
                <span class="ico_comm ico_carpark"></span>
                해수욕장
            </li>
        </ul>
    </div>
</div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=3bfa0cecde5be410aab6353aea6bfc2c"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div  
        mapOption = { 
            center: new kakao.maps.LatLng(37.498004414546934, 127.02770621963765), // 제주도 지도의 중심좌표 
            level: 3 // 지도의 확대 레벨 
        }; 

    var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

    // 항포구 마커가 표시될 좌표 배열입니다
    var portPositions = [ 
        new kakao.maps.LatLng(37.499590490909185, 127.0263723554437),
        new kakao.maps.LatLng(37.499427948430814, 127.02794423197847),
        new kakao.maps.LatLng(37.498553760499505, 127.02882598822454),
        new kakao.maps.LatLng(37.497625593121384, 127.02935713582038),
        new kakao.maps.LatLng(37.49646391248451, 127.02675574250912),
        new kakao.maps.LatLng(37.49629291770947, 127.02587362608637),
        new kakao.maps.LatLng(37.49754540521486, 127.02546694890695)                
    ];

    // 해수욕장 마커가 표시될 좌표 배열입니다
    var beachPositions = [
        new kakao.maps.LatLng(37.49966168796031, 127.03007039430118),
        new kakao.maps.LatLng(37.499463762912974, 127.0288828824399),
        new kakao.maps.LatLng(37.49896834100913, 127.02833986892401),
        new kakao.maps.LatLng(37.49893267508434, 127.02673400572665),
        new kakao.maps.LatLng(37.49872543597439, 127.02676785815386),
        new kakao.maps.LatLng(37.49813096097184, 127.02591949495914),
        new kakao.maps.LatLng(37.497680616783086, 127.02518427952202)                       
    ];    

    var markerImageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/category.png';  // 마커이미지의 주소입니다. 스프라이트 이미지 입니다
    
    portMarkers = [], // 항포구 마커 객체를 가지고 있을 배열입니다
    beachMarkers = [], // 해수욕장 마커 객체를 가지고 있을 배열입니다

        
    createportMarkers(); // 커피숍 마커를 생성하고 커피숍 마커 배열에 추가합니다
    createbeachMarkers(); // 주차장 마커를 생성하고 주차장 마커 배열에 추가합니다

    // 마커이미지의 주소와, 크기, 옵션으로 마커 이미지를 생성하여 리턴하는 함수입니다
    function createMarkerImage(src, size, options) {
        var markerImage = new kakao.maps.MarkerImage(src, size, options);
        return markerImage;            
    }

    // 좌표와 마커이미지를 받아 마커를 생성하여 리턴하는 함수입니다
    function createMarker(position, image) {
        var marker = new kakao.maps.Marker({
            position: position,
            image: image
        });
        
        return marker;  
    }   
    
    // 항포구 마커를 생성하고 커피숍 마커 배열에 추가하는 함수입니다
    function createportMarkers() {
        
        for (var i = 0; i < portPositions.length; i++) {  
            
            var imageSize = new kakao.maps.Size(22, 26),
                imageOptions = {  
                    spriteOrigin: new kakao.maps.Point(10, 0),    
                    spriteSize: new kakao.maps.Size(36, 98)  
                };     
            
            // 마커이미지와 마커를 생성합니다
            var markerImage = createMarkerImage(markerImageSrc, imageSize, imageOptions),    
                marker = createMarker(portPositions[i], markerImage);  
            
            // 생성된 마커를 커피숍 마커 배열에 추가합니다
            portMarkers.push(marker);
        }     
    }

    // 항포구 마커들의 지도 표시 여부를 설정하는 함수입니다
    function setportMarkers(map) {        
        for (var i = 0; i < portMarkers.length; i++) {  
            portMarkers[i].setMap(map);
        }        
    }


    // 해변 마커를 생성하고 주차장 마커 배열에 추가하는 함수입니다
    function createbeachMarkers() {
        for (var i = 0; i < beachPositions.length; i++) {
            
            var imageSize = new kakao.maps.Size(22, 26),
                imageOptions = {   
                    spriteOrigin: new kakao.maps.Point(10, 72),    
                    spriteSize: new kakao.maps.Size(36, 98)  
                };       
        
            // 마커이미지와 마커를 생성합니다
            var markerImage = createMarkerImage(markerImageSrc, imageSize, imageOptions),    
                marker = createMarker(beachPositions[i], markerImage);  

            // 생성된 마커를 주차장 마커 배열에 추가합니다
            beachMarkers.push(marker);        
        }                
    }

    // 해변 마커들의 지도 표시 여부를 설정하는 함수입니다
    function setbeachMarkers(map) {        
        for (var i = 0; i < beachMarkers.length; i++) {  
            beachMarkers[i].setMap(map);
        }        
    }
// 33.540855 126.690195
    // 카테고리를 클릭했을 때 type에 따라 카테고리의 스타일과 지도에 표시되는 마커를 변경합니다
    function changeMarker(type){
        
        var portMenu = document.getElementById('portMenu');
        var beachMenu = document.getElementById('beachMenu');
        
        // 커피숍 카테고리가 클릭됐을 때
        if (type === 'port') {
        
            // 항포구 카테고리를 선택된 스타일로 변경하고
            portMenu.className = 'menu_selected';
            beachMenu.className = '';
            
            // 해수욕장 마커들만 지도에 표시하도록 설정합니다
            setportMarkers(map);
            setbeachMarkers(null);
            
        } else if (type === 'beach') { // 편의점 카테고리가 클릭됐을 때
        
            // 편의점 카테고리를 선택된 스타일로 변경하고
            portMenu.className = '';
            beachMenu.className = 'menu_selected';

            
            // 편의점 마커들만 지도에 표시하도록 설정합니다
            setportMarkers(null);
            setbeachMarkers(map);
            
        }  
    } 

// 현재 위치 표시
//var lat, lon;
// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
//if (navigator.geolocation) {
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
//    navigator.geolocation.getCurrentPosition(function(position) {

//        lat = position.coords.latitude, // 위도
//        lon = position.coords.longitude; // 경도
        
//        var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
//            message = '현재 위치'; // 인포윈도우에 표시될 내용입니다
        
        // 마커와 인포윈도우를 표시합니다
//        displayMarker(locPosition, message);

        // lat와 lon 값을 폼 필드에 설정합니다
//        document.getElementById('latitude').value = lat;
//        document.getElementById('longitude').value = lon;
        
        // 폼을 자동으로 제출합니다
//        document.getElementById('locationForm').submit();
            
//        });
    
//} 

//else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    
var locPosition = new kakao.maps.LatLng(33.540855, 126.690195)//    
    //message = 'geolocation을 사용할수 없음'
    
displayMarker(locPosition, message);

//}

// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({  
        map: map, 
        position: locPosition
    }); 
    
    var iwContent ='<div style="text-align: center;">' + message + '</div>', // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new kakao.maps.InfoWindow({
        content : iwContent,
    });
    
    // 인포윈도우를 마커위에 표시합니다 
    infowindow.open(map, marker);
    
    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);   
    marker.setMap(locPosition);
}
</script>

<form action="move" method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <input type="hidden" name="latitude" id="latitude" value="">
    <input type="hidden" name="longitude" id="longitude" value="">
</form>
<div class="button">
    <a href="{% url 'map:move_map' %}">
    <img src="{% static 'images/search_2.png' %}" />
    </a>
</div> 
{% endblock %}

mysite/map/templates/map/move.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
  movemap
{% endblock %}

{% block content %}
<div id="mapwrap"> 
    <!-- 지도가 표시될 div -->
    <div id="map" style="width:75%; height:800px;"></div>
    
    <!-- 지도 위에 표시될 마커 카테고리 -->
    <div class="category">
        <ul>
            <li id="portMenu" onclick="changeMarker('port')">
                <span class="ico_comm ico_coffee"></span>
                항포구
            </li>
            <li id="beachMenu" onclick="changeMarker('beach')">
                <!-- <img src="{% static 'images/Vector-3.png' %}" alt="해수욕장 아이콘" style="width:20px;height:20px;"> -->
                <span class="ico_comm ico_carpark"></span>
                해수욕장
            </li>
        </ul>
    </div>
</div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=3bfa0cecde5be410aab6353aea6bfc2c"></script>

<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div  
        mapOption = { 
            center: new kakao.maps.LatLng(37.498004414546934, 127.02770621963765), // 제주도 지도의 중심좌표 
            level: 3 // 지도의 확대 레벨 
        }; 

    var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

    // 항포구 마커가 표시될 좌표 배열입니다
    var portPositions = [ 
        new kakao.maps.LatLng(33.40417, 126.24889),
        new kakao.maps.LatLng(33.41472, 126.25306),
        new kakao.maps.LatLng(33.41722, 126.25583),
        new kakao.maps.LatLng(33.43722, 126.27111),
        new kakao.maps.LatLng(33.52722, 126.57861),
        new kakao.maps.LatLng(33.53167, 126.59167),
        new kakao.maps.LatLng(33.53778, 126.61861),
        
        new kakao.maps.LatLng(33.54722, 126.66194),
        new kakao.maps.LatLng(33.55833, 126.73639),
        new kakao.maps.LatLng(33.39944, 126.24306),
        new kakao.maps.LatLng(33.39083, 126.22694),
        new kakao.maps.LatLng(33.37833, 126.21611),
        new kakao.maps.LatLng(33.36528, 126.19944),
        new kakao.maps.LatLng(33.27778, 126.71889),

        new kakao.maps.LatLng(33.28722, 126.75028),
        new kakao.maps.LatLng(33.30361, 126.78889),
        new kakao.maps.LatLng(33.23250, 126.33056),

        new kakao.maps.LatLng(33.32444, 126.85000),
        new kakao.maps.LatLng(33.37111, 126.87139),
        new kakao.maps.LatLng(33.38167, 126.88000),

    ];

    // 해수욕장 마커가 표시될 좌표 배열입니다
    var beachPositions = [
        new kakao.maps.LatLng(33.45000, 126.30472),
        new kakao.maps.LatLng(33.46139, 126.31028),
        new kakao.maps.LatLng(33.52583, 126.58611),
        new kakao.maps.LatLng(33.55111, 126.64861),
        new kakao.maps.LatLng(33.54333, 126.66972),
        new kakao.maps.LatLng(33.55333, 126.65139),
        new kakao.maps.LatLng(33.38972, 126.23528),
        
        new kakao.maps.LatLng(33.23111, 126.31028),
        new kakao.maps.LatLng(33.23639, 126.35667),
        new kakao.maps.LatLng(33.45222, 126.92444),
        new kakao.maps.LatLng(33.43472, 126.92306),

        new kakao.maps.LatLng(33.21083, 126.26056),
        new kakao.maps.LatLng(33.25139, 126.62333),
    ];    

    var markerImageSrc = 'https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/category.png';  // 마커이미지의 주소입니다. 스프라이트 이미지 입니다

    portMarkers = [], // 항포구 마커 객체를 가지고 있을 배열입니다
    beachMarkers = [], // 해수욕장 마커 객체를 가지고 있을 배열입니다

        
    createportMarkers(); // 커피숍 마커를 생성하고 커피숍 마커 배열에 추가합니다
    createbeachMarkers(); // 주차장 마커를 생성하고 주차장 마커 배열에 추가합니다

    // 마커이미지의 주소와, 크기, 옵션으로 마커 이미지를 생성하여 리턴하는 함수입니다
    function createMarkerImage(src, size, options) {
        var markerImage = new kakao.maps.MarkerImage(src, size, options);
        return markerImage;            
    }

    // 좌표와 마커이미지를 받아 마커를 생성하여 리턴하는 함수입니다
    function createMarker(position, image) {
        var marker = new kakao.maps.Marker({
            position: position,
            image: image
        });
        
        return marker;  
    }   

    // 항포구 마커를 생성하고 커피숍 마커 배열에 추가하는 함수입니다
    function createportMarkers() {
        
        for (var i = 0; i < portPositions.length; i++) {  
            
            var imageSize = new kakao.maps.Size(22, 26),
                imageOptions = {  
                    spriteOrigin: new kakao.maps.Point(10, 0),    
                    spriteSize: new kakao.maps.Size(36, 98)  
                };     
            
            // 마커이미지와 마커를 생성합니다
            var markerImage = createMarkerImage(markerImageSrc, imageSize, imageOptions),    
                marker = createMarker(portPositions[i], markerImage);  
            
            // 생성된 마커를 커피숍 마커 배열에 추가합니다
            portMarkers.push(marker);
        }     
    }

    // 항포구 마커들의 지도 표시 여부를 설정하는 함수입니다
    function setportMarkers(map) {        
        for (var i = 0; i < portMarkers.length; i++) {  
            portMarkers[i].setMap(map);
        }        
    }


    // 해변 마커를 생성하고 주차장 마커 배열에 추가하는 함수입니다
    function createbeachMarkers() {
        for (var i = 0; i < beachPositions.length; i++) {
            
            var imageSize = new kakao.maps.Size(22, 26),
                imageOptions = {   
                    spriteOrigin: new kakao.maps.Point(10, 72),    
                    spriteSize: new kakao.maps.Size(36, 98)  
                };       
        
            // 마커이미지와 마커를 생성합니다
            var markerImage = createMarkerImage(markerImageSrc, imageSize, imageOptions),    
                marker = createMarker(beachPositions[i], markerImage);  

            // 생성된 마커를 주차장 마커 배열에 추가합니다
            beachMarkers.push(marker);        
        }                
    }

    // 해변 마커들의 지도 표시 여부를 설정하는 함수입니다
    function setbeachMarkers(map) {        
        for (var i = 0; i < beachMarkers.length; i++) {  
            beachMarkers[i].setMap(map);
        }        
    }
    // 33.540855 126.690195
    // 카테고리를 클릭했을 때 type에 따라 카테고리의 스타일과 지도에 표시되는 마커를 변경합니다
    function changeMarker(type){
        
        var portMenu = document.getElementById('portMenu');
        var beachMenu = document.getElementById('beachMenu');
        
        // 커피숍 카테고리가 클릭됐을 때
        if (type === 'port') {
        
            // 항포구 카테고리를 선택된 스타일로 변경하고
            portMenu.className = 'menu_selected';
            beachMenu.className = '';
            
            // 해수욕장 마커들만 지도에 표시하도록 설정합니다
            setportMarkers(map);
            setbeachMarkers(null);
            
        } else if (type === 'beach') { // 편의점 카테고리가 클릭됐을 때
        
            // 편의점 카테고리를 선택된 스타일로 변경하고
            portMenu.className = '';
            beachMenu.className = 'menu_selected';

            
            // 편의점 마커들만 지도에 표시하도록 설정합니다
            setportMarkers(null);
            setbeachMarkers(map);
            
        }  
    } 


    //var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    //    mapOption = { 
    //        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
    //        level: 3 // 지도의 확대 레벨
    //    };
        
    //var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다
    
    // 마커가 표시될 위치입니다 위치 받아오기-> 현재 위치 받아와서 이동
    var lat, lon;
//        lat={{loc.lat}}
//       lon={{loc.lon}}

// 33.540855 126.690195
    var markerPosition  = new kakao.maps.LatLng(33.540855, 126.690195); 
    
    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        position: markerPosition
    });
    
    // 마커가 지도 위에 표시
    marker.setMap(map);
    // 마커가 있는 위치로 이동하기
    map.panTo(markerPosition);            


    // 아래 코드는 지도 위의 마커를 제거하는 코드입니다
    // marker.setMap(null);
</script>

<div class="button"></div>
    <a href="{% url 'map:poi_map' %}">
    <img src="{% static 'images/search_2.png' %}" />
    </a>
</div>

{% endblock %}

mysite/map/templates/map/poi.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
  POI
{% endblock %}

{% block content %}

<img src="{% static 'images/POI.png' %}" style="width:75%; height:800px;"/>

{% endblock %}

mysite/templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
  startpage
{% endblock %}

{% block content %}
<!-- button으로 변경-->
<p class="'title">위성데이터 및 CCTV를 활용한 제주 특정 지역 쓰레기 발생량 기반 POI 추천 플랫폼</p>

<!-- 지도를 표시할 div 입니다 -->
<div id="map" style="width:75%; height:800px;"></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=3bfa0cecde5be410aab6353aea6bfc2c"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 9 // 지도의 확대 레벨
    };

// 지도를 표시할 div와  지도 옵션으로  지도를 생성합니다
var map = new kakao.maps.Map(mapContainer, mapOption); 
</script>

<!-- 함께하기 버튼 -->
<div class="button">
  <a href="{% url 'map:index_map' %}">
  <img src="{% static 'images/Group_8.png' %}" />
  </a>
</div> 
</script> 
  
{% endblock %}

mysite/templates/layout.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <div class="frame">
        <div class="div">
        <div class="overlap-group">
            {% block content %}{% endblock %}
        </div>
        </div>
    </div>    
  </body>
</html>